@startuml CodigoAVoluntad
class Colectivo{
    -nombre : String
    -descripcion : String
    -ubicacion : String
    -tipoDeColectivo : TipoDeColectivo
    -proyectos : [Proyecto]

    +cargarProyecto()
}

class Proyecto{
    -titulo : String
    -descripcion : String
    -habilidadesRequeridas : [Habilidad]
    -horas : Number
    -tipoDeCompromiso : TipoCompromiso
    -modalidadDeColaboracion : ModalidadColaboracion
    -colectivo : Colectivo
    -finalizado : Boolean
}

class Colaboracion{
    -personaColaboradora : PersonaColaboradora
    -proyecto : Proyecto
}

class Habilidad{
    -titulo : String
    -codigo : String
    -descripcion : String

    +normalizarTitulo()
}

class PersonaColaboradora{
    -nombreFantasia : String
    -git : String
    -nombre : String
    -apellido : String
    -habilidades : [Habilidad]
    -presentacion : String
}

enum ModalidadColaboracion {
    GRATUITA
    INCENTIVO_ECONOMICO
    CONTRATACION_EVENTUAL
}

enum TipoCompromiso {
    TOTAL
    SEMANAL
    MENSUAL
}

enum TipoColectivo {
    FUNDACION                                 
    ONG
    ASOCIACION_BARRIAL
    ASAMBLEAS
}

Colectivo --> "*" Proyecto
PersonaColaboradora -> "*" Habilidad
Habilidad "*" <- Proyecto
Colaboracion --> Proyecto
Colaboracion --> PersonaColaboradora
Colectivo -> TipoColectivo
Proyecto --> ModalidadColaboracion
Proyecto --> TipoCompromiso

@enduml